version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: outbox-relayer-db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d devdb" ]
      interval: 5s
      retries: 5

  outbox-relayer:
    build: .
    container_name: outbox-relayer
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DATABASE: devdb
    ports:
      - "8080:8080"
    command: [ "./outbox-relayer" ]

volumes:
  pgdata:
