postgres:
  host: localhost
  port: 5432
  user: dev
  password: dev
  database: devdb

migration:
  path: internal/infra/migrations

relayer:
  batch: 2
  timeout: 1s
  maxAttempts: 5

webhook:
  url: "https://webhook.site/b080d123-474c-48c2-bff2-986a6e3e7ce2"
  authKey: ""
  timeout: 1s

schedule:
  interval: 2m

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  ttl: 24h
