postgres:
  host: localhost
  port: 5432
  user: dev
  password: dev
  database: devdb

migration:
  path: internal/infra/migrations

relayer:
  batch: 2
  timeout: 1s
  maxAttempts: 5

webhook:
  url: "https://webhook.site/5dcc9ebe-72f4-4332-bff0-94569bf9748e"
  authKey: ""
  timeout: 1s

schedule:
  interval: 2m